openapi: 3.0.0
servers: 
  - url: 'https://api-electronicdevices-313314.nw.r.appspot.com/api/v1/'
info:
  description: This API can be used to consult multiple electronic devices which could be found in different shops.
  version: "1.0.0"
  title: API-ElectronicDevices
  contact:
    email: joselugarciamarin2406@gmail.com
  license:
    name: Apache 2.0
    url: 'http://www.apache.org/licenses/LICENSE-2.0.html'
tags:
  - name: Devices
    description: Different methods of devices
  - name: Shops
    description: Different methods of shops
paths:
  /devices:
    get:
      tags:
        - Devices
      summary: Get devices
      description: Get all the devices
      operationId: getDevices
      parameters:
        - name: order
          in: query
          description: Order results by name, price, screenSize, weight, memory or storage.
          required: false
          schema:
            type: string
            enum: 
              - name
              - '-name'
              - price
              - '-price'
              - screenSize
              - '-screenSize'
              - weight
              - '-weight'
              - memory
              - '-memory'
              - storage
              - '-storage'
        - name: brand
          in: query
          description: Query to filter by brand
          required: false
          schema:
            type: string
        - name: deviceType
          in: query
          description: Query to filter by device type
          required: false
          schema:
            type: string
        - name: OS
          in: query
          description: Query to filter by OS
          required: false
          schema:
            type: string
        - name: offset
          in: query
          description: Offset of the results
          required: false
          schema:
            type: integer
            format: int32
            minimum: 0
        - name: limit
          in: query
          description: Maximum number of results
          required: false
          schema:
            type: integer
            format: int32
            minimum: 0
      responses:
        '200':
          description: Search resutl matching criteria
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Device'
        '404':
          description: Not found
    post:
      tags:
        - Devices
      summary: Create a device
      description: Create a device
      operationId: createDevice
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Device'
        description: Device to create
        required: true
      responses:
        '201':
          description: Device created
        '400':
          description: Bad request
    put:
      tags:
        - Devices
      summary: Update a device
      description: Update a device
      operationId: updateDevice
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Device'
      responses:
        '204':
          description: Device update
        '400':
          description: Device not update
  '/devices/{id}':
    get:
      tags: 
        - Devices
      summary: Get a device by id
      description: Get a device by id
      operationId: getDeviceById
      parameters: 
        - name: id
          in: path
          description: Id of the device
          required: true
          schema:
            type: integer
            format: int32
            minimum: 0
      responses:
        '200':
          description: Device found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Device'
        '400':
          description: Device not found
    delete:
      tags:
        - Devices
      summary: Delete a device
      description: Delete a device
      operationId: deleteDevice
      parameters: 
        - name: id
          in: path
          description: Id of the device
          required: true
          schema:
            type: integer
            format: int32
            minimum: 0
      responses:
        '204':
          description: Device deleted
        '404':
          description: Device not found
  /shops:
    get:
      tags: 
      - Shops
      summary: Get all the shops
      description: Get all the shops
      operationId: getAllShops
      parameters:
        - name: order
          in: query
          description: Order result by name
          required: false
          schema:
            type: string
            enum: 
              - name
              - '-name'
        - name: isEmpty
          in: query
          description: Filter shops with no devices
          required: false
          schema:
            type: boolean
        - name: name
          in: query
          description: Filter shops by name
          required: false
          schema:
            type: string
      responses:
        '200':
          description: Search results matching criteria
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Shop'
        '400':
          description: Bad request
    post:
      tags:
        - Shops
      summary: Create a shop
      description: Create a shop
      operationId: createShop
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/ShopEmpty'
        required: true
      responses:
        '201':
          description: Shop created
        '400':
          description: Bad request
    put:
      tags: 
        - Shops
      summary: Update a shop
      description: Update a shop
      operationId: updateShop
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/ShopEmpty'
      responses:
        '204':
          description: Shop update
        '400':
          description: Bad request
        '404':
          description: Shop not found
  '/shops/{id}':
    get:
      tags:
        - Shops
      summary: Get a shop by id
      description: Get a shop by id
      operationId: getShopById
      parameters: 
        - name: id
          in: path
          description: Id of the shop
          required: true
          schema:
            type: integer
            format: int32
            minimum: 0
      responses:
        '204':
          description: Shop found
        '404':
          description: Shop not found
    delete:
      tags: 
        - Shops
      summary: Delete a shop
      description: Delete a shop
      operationId: deleteShop
      parameters: 
        - name: id
          in: path
          description: Id of the shop
          required: true
          schema:
            type: integer
            format: int32
            minimum: 0
      responses:
        '204':
          description: Shop delete
        '404':
          description: Shop not found
  '/shops/{shopId}/{deviceId}':
    post:
      tags: 
        - Shops
      summary: Add device to shop
      description: Add device to shop
      operationId: addDeviceToShop
      requestBody:
        content:
          text/plain:
            schema:
              type: string
      parameters: 
        - name: shopId
          in: path
          description: Id of the shop
          required: true
          schema:
            type: integer
            format: int32
            minimum: 0
        - name: deviceId
          in: path
          description: Id of the device
          required: true
          schema:
            type: integer
            format: int32
            minimum: 0
      responses:
        '201':
          description: Device added to the shop
        '400':
          description: Bad request
        '404':
          description: Shop or device not found
    delete:
      tags: 
        - Shops
      summary: Delete a device from a shop
      description: Delete a device from a shop
      operationId: deleteDeviceFromShop
      parameters: 
        - name: shopId
          in: path
          description: Id of the shop
          required: true
          schema:
            type: integer
            format: int32
            minimum: 0
        - name: deviceId
          in: path
          description: Id of the device
          required: true
          schema:
            type: integer
            format: int32
            minimum: 0
      responses:
        '204':
          description: Device delete from shop
        '404':
          description: Shop or device not found
components:
  schemas:
    Device:
      type: array
      items:
        type: object
        required: 
          - name
        properties:
          id:
            type: integer
          name:
            type: string
          brand:
            type: string
          price: 
            type: number
          screenSize:
            type: number
          weight:
            type: number
          deviceType:
            type: string
          storage:
            type: integer
          processor:
            type: string
          memory:
            type: integer
          OS:
            type: string
          setColors:
            type: array
            items:
              type: string
          camera:
            type: string
      example:
        id: 1
        name: Galaxy s20 FE
        brand: Samsung
        price: 649.0
        screenSize: 6.5
        weight: 0.19
        deviceType: MOBILE
        storage: 128
        processor: Samsung Exynos 990
        memory: 6
        setColors: [Cloud Orange, Cloud Red, Cloud white, Cloud Navy]
        camera: "Principal 12Mp"
        os: Android
    Shop: 
      type: array
      items:
        type: object
        required: 
          - name
        properties:
          id: 
            type: integer
          name:
            type: string
          url:
            type: string
          deviceList:
            type: array
            items:
              type: object
              required: 
                - name
              properties:
                id:
                  type: integer
                name:
                  type: string
                brand:
                  type: string
                price: 
                  type: number
                screenSize:
                  type: number
                weight:
                  type: number
                deviceType:
                  type: string
                storage:
                  type: integer
                processor:
                  type: string
                memory:
                  type: integer
                OS:
                  type: string
                setColors:
                  type: array
                  items:
                    type: string
                camera:
                  type: string
        example: 
          - id: 7
            name: Worte
            url: https://www.worten.es
            devices:
              - id: 1
                name: Galaxy s20 FE
                brand: Samsung
                price: 649.0
                screenSize: 6.5
                weight: 0.19
                deviceType: MOBILE
                storage: 128
                processor: Samsung Exynos 990
                memory: 6
                setColors: [Cloud Orange, Cloud Red, Cloud white, Cloud Navy]
                camera: "Principal 12Mp"
                OS: Android
    ShopEmpty: 
      type: object
      required: 
        - name
      properties:
        id:
          type: integer
        name:
          type: string
        url:
          type: string